#!/bin/bash

#######################################
# FUNCTIONS
#######################################

start () {
  (
    trap 'kill 0' SIGINT ;
    cd ./frontend &&
    npm run dev &
    cd ./backend &&
    eval "$(conda shell.bash hook)" &&
    conda deactivate &&
    conda activate django-nextjs &&
    python ./manage.py runserver
  )
}


#######################################
# MENU
#######################################

case "$1" in
    start)
      start
      ;;
    *)
        cat << EOF

Command line interface for the Docker-based web development environment demo.

Usage:
    app <command> [options] [arguments]

Available commands:
    start ..................................... Start the containers

EOF
  exit
  ;;
esac
