version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443
    volumes:
      - app:/var/www/app
      - ./.docker/local/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/local/nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # Python/Django Service
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: "/var/www/app/./local run_backend"
    expose:
      - 8000
    volumes:
      - app:/var/www/app

  # Node/Next.js Service
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    command: "/var/www/app/./local run_frontend"
    expose:
      - 3000
    volumes:
      - app:/var/www/app

volumes:
  app:
