from django.urls import path
from .views import (
    CommentsAPIView,
    CommentsByArticleAPIView,
    CommentUpvoteAPIView,
    CommentDownvoteAPIView,
    ParentCommentsByArticleAPIView,
    CommentsByPIDAPIView,
    CommentByIDAPIView,
    CommentFormAPIView
)

urlpatterns = [
    path(
        'comments',
        CommentsAPIView.as_view(),
        name='comments'
    ),
    path(
        'comments/<str:slug>',
        CommentsByArticleAPIView.as_view(),
        name='comments'
    ),
    path(
        'comment/upvote/<int:cid>',
        CommentUpvoteAPIView.as_view(),
        name='comments'
    ),
    path(
        'comment/downvote/<int:cid>',
        CommentDownvoteAPIView.as_view(),
        name='comments'
    ),
    path(
        'comments/<slug:slug>/parents',
        ParentCommentsByArticleAPIView.as_view(),
        name='comments'
    ),
    path(
        'comment/<int:cid>',
        CommentByIDAPIView.as_view(),
        name='comments'
    ),
    path(
        'comment/pid/<int:cid>',
        CommentsByPIDAPIView.as_view(),
        name='comments'
    ),
    path(
        'comment/<slug:slug>/form',
        CommentFormAPIView.as_view(),
        name='comments'
    )
]
