from django.urls import path
from .views import (
    ArticleSimpleListAPIView,
    ArticleListAPIView,
    ArticlesByTagAPIView,
    ArticlesBySearchAPIView,
    ArticleDetailAPIView,
    ArticleLikesAPIView,
    SubscribeToArticleAPIView,
    TagsAPIView,
)

urlpatterns = [
    path(
        'articles',
        ArticleListAPIView.as_view(),
        name='articles'
    ),
    path(
        'articles/simple',
        ArticleSimpleListAPIView.as_view(),
        name='articles'
    ),
    path(
        'tags/all',
        TagsAPIView.as_view(),
        name='articles'
    ),
    path(
        'articles/tagged/<slug:slug>',
        ArticlesByTagAPIView.as_view(),
        name='articles'
    ),
    path(
        'articles/search/<str:search>',
        ArticlesBySearchAPIView.as_view(),
        name='articles'
    ),
    path(
        'articles/<slug:slug>',
        ArticleDetailAPIView.as_view(),
        name='articles'
    ),
    path(
        'articles/like/<slug:slug>',
        ArticleLikesAPIView.as_view(),
        name='articles'
    ),
    path(
        'subscribers',
        SubscribeToArticleAPIView.as_view(),
        name='articles'
    ),
]
