# Generated by Django 4.2.6 on 2023-10-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_alt',
            field=models.CharField(max_length=1024),
        ),
    ]
