# Generated by Django 4.2.1 on 2023-05-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_article_content_type_alter_article_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content_type",
            field=models.CharField(
                choices=[("blog", "Blog Post"), ("page", "Page")],
                default="blog",
                max_length=12,
            ),
        ),
    ]
