version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.docker/local/nginx/certs:/etc/nginx/certs
      - ./.docker/local/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # PostgreSQL Service
  db:
    restart: always
    build:
      context: .
      dockerfile: db.Dockerfile
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Service
  redis:
    restart: always
    image: redis:latest
    ports:
      - 8000:8000

  # Python/Django Service
  backend:
    restart: always
    build:
      context: .
      dockerfile: backend.Dockerfile
    depends_on:
      - db
      - redis
    command: "/./loosed ${BACKEND_ACTION}"
    expose:
      - 8000
    volumes:
      - ./app/backend:/app/backend
      - ./app/mdx:/app/backend/mdx
      - ./app/media:/app/backend/static
      - ./loosed:/loosed

  # Node/Next.js Service
  frontend:
    restart: always
    build:
      context: .
      dockerfile: frontend.Dockerfile
      target: runner
    command: "/./loosed ${FRONTEND_ACTION}"
    depends_on:
      - backend
    expose:
      - 3000
    volumes:
      - ./app/frontend:/home/node
      - ./app/mdx:/home/node/src/mdx
      - ./app/media:/home/node/public
      - ./loosed:/loosed

# Volumes
volumes:
  app:
  postgres_data:
