# Generated by Django 4.0.4 on 2022-05-30 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_image_alt'),
        ('comments', '0002_remove_comment_id_alter_comment_cid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='page',
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
            preserve_default=False,
        ),
    ]
