# Generated by Django 4.2.1 on 2023-05-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0007_alter_comment_options_remove_comment_pid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["cid"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=2000),
        ),
    ]
