# Generated by Django 4.0.4 on 2022-05-29 04:49

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(default='', upload_to=articles.models.get_upload_path),
            preserve_default=False,
        ),
    ]
