# Generated by Django 4.0.4 on 2022-05-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.BigIntegerField()),
                ('pid', models.BigIntegerField()),
                ('author', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=255)),
                ('page', models.SlugField(max_length=255)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
