# Generated by Django 4.0.4 on 2022-05-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_comment_page_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
